title: Awesome title
author: TVMTam
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
github_username:  TVMTam # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-midnight
title: Awesome title
author: TVMTam
description: A short description about this site&#58; "It's still underconstruction"
          # to add colon : in title, use < &#58; > instead. there's no way around it. it's a yaml problem
